nome = str(input('Digite o seu nome completo:')).strip()
print('Analisando seu nome...')
print('Seu nome em letras MAIUSCULAS é {}'.format(nome.upper()))
print('Seu nome em letras minusculas é {}'.format(nome.lower()))
print('Voce possui {} letras no seu nome'.format(len(nome)-nome.count(' ')))
separa=nome.split()
print('Seu primeiro nome é {} e tem {} letras'.format(separa[0], len(separa[0])))
