a= input('Digite algo: ')
print('O tipo primitivo desse valor é',type(a))
print('So tem espaços?',a.isspace())
print('E um numero?',a.isnumeric())
print('E alfabeto?',a.isalpha())
print('E alfanumerico?',a.isalnum())
print('Possui todas as letras maiusculas?',a.isupper())
print('Possui todas as letras minusculas?',a.islower())
print("Esta palavra está capitalizada?",a.istitle())
