print('INFORMAÇOES PESSOAIS')
print("")
nome = input('Qual é o seu nome?')
idade = input('Qual é a sua idade?')
peso = input('Qual é o seu peso?')
print('')
print("Seu nome é",nome,",voce tem",idade,"e pesa",peso,"Kg")
