nome= str(input('Digite seu nome:'))
nome = nome.replace('Isaac','Ysalucky')
print(nome)
print(nome[0],nome[1],nome[2],nome[3],nome[4],nome[5],nome[6],nome[7])
print('No seu nome possui',nome.count('i'))
print('',len(nome))
print('',())
print('',())
print('',())
print('',())
print('{} seu nome no hebraico é יצחק'.format(nome))
