print('TIPOS PRIMITIVOS')
print('')
f = float(input('Digite um valor: '))
print('Em float é', f)
print('')
s = str(input('Digite um valor: '))
print('Em str é', s)
print('')
b = bool(input('Digite um valor: '))
print('Em bool é', b)
print('')
i = int(input('Digite um valor: '))
print('Em int é', i)
print('')
n = input('Digite um valor: ')
print('Possui algarismos?',n.isnumeric())
print('')
n1=input('Digite um valor: ')
print('Possui letras do alfabeto?',n.isalpha())
print('')
n2=input('Digite um valor: ')
print("Possui letras ou numeros?",n.isalnum())
